version: '3.7'
services:
  aktin-client:
    build: .
    environment:
      BROKER_REQUEST_MEDIATYPE: ${BROKER_REQUEST_MEDIATYPE:-text}
      BROKER_RESULT_MEDIATYPE: ${BROKER_RESULT_MEDIATYPE:-application/json}
      BROKER_ENDPOINT_URI: ${BROKER_ENDPOINT_URI:-http://aktin-broker:8080/broker/}
      CLIENT_AUTH_CLASS: ${CLIENT_AUTH_CLASS:-org.aktin.broker.client2.auth.ApiKeyAuthentication}
      CLIENT_AUTH_PARAM: ${CLIENT_AUTH_PARAM:-xxxApiKey123}
      CLIENT_WEBSOCKET_RECONNECT_SECONDS: ${CLIENT_WEBSOCKET_RECONNECT_SECONDS:-10}
      CLIENT_WEBSOCKET_RECONNECT_POLLING: ${CLIENT_WEBSOCKET_RECONNECT_POLLING:-true}
      PROCESS_TIMEOUT_SECONDS: ${PROCESS_TIMEOUT_SECONDS:-60}
      PROCESS_COMMAND: ${PROCESS_COMMAND:-/opt/codex-aktin/call-flare.sh}
      PROCESS_ARGS: ${PROCESS_ARGS:-10}
      FLARE_BASE_URL: ${FLARE_BASE_URL:-http://node-flare:5000}
